# If you want to have multiserver support this early in development use a
# single mysql for all servers in your BungeeCord network.


#Database name: It is the Mysql Database name
DatabaseName: 'minecraft'
#Mysql Port if using Mysql
MysqlPort: '3306'

#Mysql Username if using Mysql
MysqlUser: 'root'
#Mysql Password if using Mysql
MysqlPass: ''
#Database Table Prefix
DBPrefix: 'jaggygold_'
#require ssl
useSSL: false