name: JaggyGold
main: org.jaggy.gold.Main
version: 1.0-SNAPSHOT
author: Quirkylee, Markjat
softdepend: [Votifier]

commands:
   goldshop:
      description: shop command
      aliases: shop
      usage: /goldshop
   gold:
      description: Gold Manager command
      usage: /gold
permissions:
    jaggygold.admin:
        description: Gives access to gold command.
        default: op